resources:
- name: git-repo
  type: git
  icon: github
  check_every: 30s
  source:
    uri: https://github.com/rokibulislaam/concourse-codebucket.git
    branch: feature/auto-set-pipeline

jobs:
- name: trigger-on-merge-file-change
  plan:
  - get: git-repo
    trigger: true
    version: every
    passed: []
  - set_pipeline: pipeline
    file: git-repo/hello-world.yaml
