resources:
  - name: repo
    type: git
    icon: github
    source:
      uri: https://github.com/rokibulislaam/concourse-codebucket.git

jobs:
  - name: git-trigger-job
    plan:
      - get: repo
        trigger: true # tell Concourse to trigger this job when new versions are emitted
      - task: git-trigger-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          inputs:
            - name: repo
          run:
            path: sh
            args: 
              - -ec
              - |
                cat .git/ref
                # # Retrieve Git metadata
                # cd repo
                # commit_hash=$(git rev-parse HEAD)
                # author=$(git log -1 --pretty=format:'%an')
                # committer=$(git log -1 --pretty=format:'%cn')
                # branch=$(git rev-parse --abbrev-ref HEAD)
                # message=$(git log -1 --pretty=format:'%s')
                # url=$(git config --get remote.origin.url)
                
                # # Use the metadata as needed
                # echo "Commit Hash: $commit_hash"
                # echo "Author: $author"
                # echo "Committer: $committer"
                # echo "Branch: $branch"
                # echo "Message: $message"
                # echo "URL: $url"
