resources:
  - name: git-repo
    type: git
    icon: github
    # check_every: 30s
    source:
      uri: https://github.com/rokibulislaam/concourse-codebucket.git
      branch: feature/auto-set-pipeline
jobs:
  - name: auto-set-pipeline-on-merge
    plan:
      - get: git-repo
        trigger: true
      - set_pipeline: self
        file: git-repo/pipeline.yaml

  - name: hello-world-job
    plan:
      - task: hello-world-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          outputs:
            - name: the-artifact
          run:
            path: sh
            args:
              - -cx
              - |
                ls -l .
                echo "a few new words have been added! hello from another step! a" > the-artifact/message
      - task: read-the-artifact
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          inputs:
            - name: the-artifact
          run:
            path: sh
            args:
              - -cx
              - |
                ls -l .
                cat the-artifact/message
