resources:
  - name: git-repo
    type: git
    icon: github
    check_every: 10s
    source:
      uri: https://github.com/rokibulislaam/concourse-codebucket.git
      branch: feature/auto-set-pipeline

jobs:
  - name: trigger-on-merge
    plan:
      - get: git-repo
        trigger: true
        version: every
      - set_pipeline: self
        file: git-repo/self.yaml
        

  - name: hello-world-job
    plan:
      - get: git-repo
        passed: ['trigger-on-merge']
        trigger: true
      - task: hello-world-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          outputs:
            - name: the-artifact
          run:
            path: sh
            args:
              - -cx
              - |
                ls -l .
                echo "The file has been changed once more, so it should be reflected in the next version i.e. V4!!" > the-artifact/message
      - task: read-the-artifact
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          inputs:
            - name: the-artifact
          run:
            path: sh
            args:
              - -cx
              - |
                ls -l .
                cat the-artifact/message
     
